development:
  adapter: postgresql
  encoding: unicode
  database: coffee_reviews_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: coffee_reviews_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: coffee_reviews_prod
  pool: 5
